# Docker Compose file reference: https://docs.docker.com/compose/compose-file/
version: '3.1'

networks:
  public:
    driver: overlay
    driver_opts:
      encrypted: "true"
  private:
    driver: overlay
    driver_opts:
      encrypted: "true"

secrets:
  ch13_multi_tier_app-POSTGRES_PASSWORD: 
    external: true

volumes:
  db-data:

services:

  postgres:
      image: postgres:9.6.6
      networks:
        - private
      volumes:
             - db-data:/var/lib/postgresql/data
      secrets:
        - source: ch13_multi_tier_app-POSTGRES_PASSWORD
          target: POSTGRES_PASSWORD
          # note: world readable because postgres user (uid: 999) needs to read the file
          mode: 0444
      environment:
          POSTGRES_USER: 'exercise'
          POSTGRES_PASSWORD_FILE: '/run/secrets/POSTGRES_PASSWORD'
          POSTGRES_DB: 'exercise'

  api:
      image: ${IMAGE_REPOSITORY:-dockerinaction/ch13_multi_tier_app}:api
      #build:
      #  context: .
      #  dockerfile: api/Dockerfile
      networks:
        - public
        - private
      ports:
        - "8080:80"
        # https://docs.docker.com/compose/compose-file/#long-syntax-1
        #- target: 80
        #  published: 8080
        #  protocol: tcp
        #  mode: ingress
      secrets:
        - source: ch13_multi_tier_app-POSTGRES_PASSWORD
          target: POSTGRES_PASSWORD
          mode: 0440
      environment:
        POSTGRES_HOST: 'postgres'
        POSTGRES_PORT: '5432'
        POSTGRES_USER: 'exercise'
        POSTGRES_DB: 'exercise'
        POSTGRES_SSLMODE: 'disable'
        POSTGRES_PASSWORD_FILE: '/run/secrets/POSTGRES_PASSWORD'
        #uncomment to print debug.  note: will print DB connection info to stdout/logs, including password
        DEBUG: 'true'
      depends_on:
        - postgres
      deploy:
          replicas: 2
          update_config:
              parallelism: 1
              delay: 5s
          restart_policy:
              condition: on-failure

  shell:
      image: alpine:3.6
      command: sleep 3600
      networks:
        - private
